/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/layout'
import { Route as ProtectedPostsIndexRouteImport } from './routes/_protected/posts/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPostsPostidIndexRouteImport } from './routes/_protected/posts/$postid/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPostsIndexRoute = ProtectedPostsIndexRouteImport.update({
  id: '/_protected/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/_protected/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPostsPostidIndexRoute =
  ProtectedPostsPostidIndexRouteImport.update({
    id: '/_protected/posts/$postid/',
    path: '/posts/$postid/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/layout': typeof ProtectedLayoutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/posts/': typeof ProtectedPostsIndexRoute
  '/posts/$postid/': typeof ProtectedPostsPostidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/layout': typeof ProtectedLayoutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/posts': typeof ProtectedPostsIndexRoute
  '/posts/$postid': typeof ProtectedPostsPostidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/_protected/layout': typeof ProtectedLayoutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/posts/': typeof ProtectedPostsIndexRoute
  '/_protected/posts/$postid/': typeof ProtectedPostsPostidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/layout'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/dashboard/'
    | '/posts/'
    | '/posts/$postid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/layout'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/dashboard'
    | '/posts'
    | '/posts/$postid'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/_protected/layout'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/_protected/dashboard/'
    | '/_protected/posts/'
    | '/_protected/posts/$postid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedPostsIndexRoute: typeof ProtectedPostsIndexRoute
  ProtectedPostsPostidIndexRoute: typeof ProtectedPostsPostidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/layout': {
      id: '/_protected/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/posts/': {
      id: '/_protected/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof ProtectedPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/posts/$postid/': {
      id: '/_protected/posts/$postid/'
      path: '/posts/$postid'
      fullPath: '/posts/$postid/'
      preLoaderRoute: typeof ProtectedPostsPostidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProtectedLayoutRoute: ProtectedLayoutRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedPostsIndexRoute: ProtectedPostsIndexRoute,
  ProtectedPostsPostidIndexRoute: ProtectedPostsPostidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
