packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@eslint/js": ^9.39.2
  "@hono/node-server": ^1.19.9
  "@orpc/client": ^1.13.4
  "@orpc/contract": ^1.13.4
  "@orpc/openapi": ^1.13.4
  "@orpc/openapi-client": ^1.13.4
  "@orpc/server": ^1.13.4
  "@orpc/tanstack-query": ^1.13.4
  "@base-ui/react": ^1.2.0
  "@fontsource-variable/jetbrains-mono": ^5.2.8
  "@hugeicons/core-free-icons": ^3.1.1
  "@hugeicons/react": ^1.1.5
  "@orpc/valibot": ^1.13.4
  "@tailwindcss/vite": ^4.1.18
  "@tanstack/react-form": ^1.28.0
  "@tanstack/react-query": ^5.90.20
  "@tanstack/react-router": ^1.159.3
  "@tanstack/router-devtools": ^1.159.3
  "@tanstack/router-plugin": ^1.159.3
  "@types/eslint-config-prettier": ^6.11.3
  "@types/node": ^25.2.2
  "@types/pg": ^8.16.0
  "@types/react": ^19.2.13
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react-swc": ^4.2.3
  better-auth: ^1.4.18
  class-variance-authority: ^0.7.1
  dotenv-cli: ^11.0.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  drizzle-valibot: ^0.4.2
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.8.3
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.8.3
  globals: ^17.3.0
  hono: ^4.11.9
  next-themes: ^0.4.6
  pg: ^8.18.0
  prettier: ^3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  shx: ^0.4.0
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tailwindcss-animate: ^1.0.7
  tsdown: ^0.20.3
  tsx: ^4.21.0
  turbo: ^2.8.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  url-join: ^5.0.0
  valibot: ^1.2.0
  vite: ^7.3.1

ignoredBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  brace-expansion@<=2.0.1: ">=2.0.2"
  diff@<=8.0.2: ">=8.0.3"
  esbuild@<=0.24.2: ">=0.25.0"
  seroval@<=1.3.2: ">=1.4.1"
